In [ ]:
!pip install Pillow

In [ ]:
import numpy as np

filePath = 'pathToFile'
data = np.load(filePath)

In [ ]:
import os

newFolderPathAll = 'folder to extract to'

Just... why am I doing this in google colab... just download the npy file and do it on my own computer via jupyter...

In [ ]:
from PIL import Image

for index in range(data.shape[0]):
  imageData = data[index]
  image = Image.fromarray(imageData.astype(np.uint8))
  imgPath = os.path.join(newFolderPathAll, f'image_{index}.png')
  image.save(imgPath)

ValueError: invalid literal for int() with base 10: np.str_('image_0_fake.png')

In [ ]:
print(data[0])

[[[207 215 212]
  [205 215 214]
  [210 215 214]
  ...
  [193 199 196]
  [197 200 193]
  [191 196 197]]

 [[209 210 214]
  [207 210 218]
  [211 214 217]
  ...
  [197 195 197]
  [198 197 197]
  [194 196 200]]

 [[205 213 212]
  [206 214 212]
  [210 214 214]
  ...
  [196 196 197]
  [195 198 192]
  [193 196 194]]

 ...

 [[170 178 172]
  [176 177 177]
  [171 177 174]
  ...
  [183 180 181]
  [178 182 179]
  [179 182 183]]

 [[173 176 165]
  [177 178 172]
  [177 179 167]
  ...
  [179 183 177]
  [183 184 170]
  [182 181 180]]

 [[170 172 164]
  [169 170 167]
  [175 176 166]
  ...
  [174 174 171]
  [176 178 171]
  [171 178 173]]]


In [ ]:
print(type(data[0]), data[0].shape)

<class 'numpy.ndarray'> (256, 256, 3)
